# Generated by Django 2.2 on 2021-08-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books_favorited',
            new_name='favorited_by',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books_uploaded',
            new_name='uploaded_by',
        ),
    ]
