# Generated by Django 2.2 on 2021-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
